name: Threads Automation

on:
  # schedule:
  #   - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload-threads:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r threads/requirements.txt

      - name: Run Threads Upload
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          THREADS_ACCESS_TOKEN: ${{ secrets.THREADS_ACCESS_TOKEN }}
          THREADS_USER_ID: ${{ secrets.THREADS_USER_ID }}
        run: |
          cd threads
          python main.py

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add master_videos.json

          git diff --staged --quiet || git commit -m "Threads upload status updated"

      - name: Push Changes
        run: git push
