name: Youtube Automation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  upload:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Dependencies
        run: |
          cd youtube
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Automation
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}

        run: |
          cd youtube
          python main.py

      - name: Commit Updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add master_videos.json

          git diff --cached --quiet || git commit -m "Update video processing status"

          git push
